"""Dynamically generated configuration forms for algorithm config models.

Builds a Qt form from the fields of an :class:`~pyRadPlan.core.AlgorithmConfig`
subclass (as generated by :meth:`~pyRadPlan.core.ConfigurableAlgorithm.config_model`),
mapping field types and constraints to suitable editor widgets. Edits are
validated live through a draft model instance (``validate_assignment``), so
invalid values are flagged without ever producing an inconsistent config.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Literal, Mapping, Optional, Union, get_args, get_origin

from pydantic import ValidationError
from PySide6.QtCore import Signal
from PySide6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QDialog,
    QDialogButtonBox,
    QFormLayout,
    QLabel,
    QLineEdit,
    QScrollArea,
    QSpinBox,
    QVBoxLayout,
    QWidget,
)

from pyRadPlan.core import AlgorithmConfig, field_constraints
from ._base import AdaptiveDoubleSpinBox, parse_number_list

logger = logging.getLogger(__name__)

_INT_LIMIT = 2**31 - 1
_FLOAT_LIMIT = 1e12


def _unwrap_optional(annotation: Any) -> tuple[Any, bool]:
    """Strip Optional[...] from an annotation, returning (inner, was_optional)."""
    if get_origin(annotation) is Union:
        args = [a for a in get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return args[0], True
        return annotation, type(None) in get_args(annotation)
    return annotation, False


class ConfigFormWidget(QWidget):
    """Auto-generated editor form for an :class:`AlgorithmConfig` subclass.

    Parameters
    ----------
    model_cls:
        The configuration model class (``SomeEngine.config_model()``).
    initial:
        Initial values (e.g. the current ``pln.prop_dose_calc`` entries).
        Invalid entries are dropped with a log message.
    exclude:
        Field names to leave out of the form (e.g. nested sub-configurations
        that are edited elsewhere).
    parent:
        Optional Qt parent widget.
    """

    #: Emitted with (field_name, value) after a successful edit.
    value_changed = Signal(str, object)
    #: Emitted with (field_name, message) when an edit fails validation.
    validation_failed = Signal(str, str)

    def __init__(
        self,
        model_cls: type[AlgorithmConfig],
        initial: Optional[Mapping[str, Any]] = None,
        exclude: Optional[set[str]] = None,
        parent: Optional[QWidget] = None,
    ) -> None:
        super().__init__(parent)
        self._model_cls = model_cls
        self._exclude = set(exclude or ())
        self._draft = self._validate_initial(model_cls, dict(initial or {}))
        self._editors: dict[str, QWidget] = {}

        form = QFormLayout(self)
        form.setContentsMargins(0, 0, 0, 0)
        form.setVerticalSpacing(4)

        for name, info in model_cls.model_fields.items():
            if name in self._exclude:
                continue
            editor = self._create_editor(name, info)
            if editor is None:
                continue
            self._editors[name] = editor
            form.addRow(QLabel(self._label_for(name, info)), editor)

        if not self._editors:
            form.addRow(QLabel("No configurable parameters."))

    @staticmethod
    def _validate_initial(
        model_cls: type[AlgorithmConfig], initial: dict[str, Any]
    ) -> AlgorithmConfig:
        try:
            return model_cls.model_validate(initial)
        except ValidationError as exc:
            logger.info(
                "Some initial values are invalid for %s and will be ignored: %s",
                model_cls.__name__,
                exc,
            )
        draft = model_cls()
        for key, value in initial.items():
            try:
                setattr(draft, key, value)
            except (ValidationError, ValueError):
                continue
        return draft

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def model_cls(self) -> type[AlgorithmConfig]:
        """The configuration model class this form edits."""
        return self._model_cls

    def config(self) -> AlgorithmConfig:
        """Get the draft model instance holding the current form state."""
        return self._draft

    def values(self) -> dict[str, Any]:
        """Get the entries that were set initially or edited by the user."""
        return {
            name: getattr(self._draft, name)
            for name in self._draft.model_fields_set
            if name not in self._exclude
        }

    # ------------------------------------------------------------------
    # Editor construction
    # ------------------------------------------------------------------

    @staticmethod
    def _label_for(name: str, info) -> str:
        meta = field_constraints(info).get("param_meta")
        if meta is not None and meta.label:
            return meta.label
        return name.replace("_", " ").capitalize() + ":"

    def _create_editor(self, name: str, info) -> Optional[QWidget]:
        constraints = field_constraints(info)
        meta = constraints.get("param_meta")
        if meta is not None and not meta.configurable:
            return None

        annotation, optional = _unwrap_optional(info.annotation)
        value = getattr(self._draft, name)
        origin = get_origin(annotation)

        editor: Optional[QWidget] = None
        if annotation is bool:
            editor = self._make_bool_editor(name, value)
        elif annotation is int:
            editor = self._make_int_editor(name, value, constraints)
        elif annotation is float:
            editor = self._make_float_editor(name, value, constraints)
        elif origin is Literal:
            editor = self._make_choice_editor(name, value, get_args(annotation))
        elif annotation is str:
            editor = self._make_str_editor(name, value, optional)
        elif origin is list and get_args(annotation) and get_args(annotation)[0] in (int, float):
            editor = self._make_list_editor(name, value, get_args(annotation)[0])
        else:
            # Unsupported field types get a generic JSON editor instead of
            # silently disappearing from the form.
            editor = self._make_fallback_editor(name, value)

        if editor is not None and constraints.get("description"):
            editor.setToolTip(constraints["description"])
        return editor

    def _make_bool_editor(self, name: str, value: Any) -> QCheckBox:
        box = QCheckBox()
        box.setChecked(bool(value))
        box.toggled.connect(lambda checked: self._set_value(name, checked))
        return box

    def _make_int_editor(self, name: str, value: Any, constraints: dict) -> QSpinBox:
        spin = QSpinBox()
        low = constraints.get("ge", constraints.get("gt", -_INT_LIMIT))
        high = constraints.get("le", constraints.get("lt", _INT_LIMIT))
        if "gt" in constraints:
            low = constraints["gt"] + 1
        if "lt" in constraints:
            high = constraints["lt"] - 1
        spin.setRange(int(low), int(high))
        if value is not None:
            spin.setValue(int(value))
        spin.valueChanged.connect(lambda v: self._set_value(name, v))
        return spin

    def _make_float_editor(
        self, name: str, value: Any, constraints: dict
    ) -> AdaptiveDoubleSpinBox:
        spin = AdaptiveDoubleSpinBox()
        low = constraints.get("ge", constraints.get("gt", -_FLOAT_LIMIT))
        high = constraints.get("le", constraints.get("lt", _FLOAT_LIMIT))
        spin.setRange(float(low), float(min(high, _FLOAT_LIMIT)))
        if value is not None:
            spin.setValue(float(min(value, _FLOAT_LIMIT)))
        spin.valueChanged.connect(lambda v: self._set_value(name, v))
        return spin

    def _make_choice_editor(self, name: str, value: Any, choices: tuple) -> QComboBox:
        combo = QComboBox()
        combo.addItems([str(c) for c in choices])
        if value is not None:
            combo.setCurrentText(str(value))
        combo.currentTextChanged.connect(lambda text: self._set_value(name, text))
        return combo

    def _make_str_editor(self, name: str, value: Any, optional: bool = False) -> QLineEdit:
        edit = QLineEdit(str(value) if value is not None else "")
        if optional:
            edit.editingFinished.connect(lambda: self._set_value(name, edit.text() or None))
        else:
            edit.editingFinished.connect(lambda: self._set_value(name, edit.text()))
        return edit

    def _make_list_editor(self, name: str, value: Any, item_type: type) -> QLineEdit:
        text = " ".join(f"{v:g}" for v in value) if value else ""
        edit = QLineEdit(text)

        def _commit() -> None:
            try:
                parsed = parse_number_list(edit.text(), item_type)
            except ValueError as exc:
                self._flag_error(name, str(exc))
                return
            self._set_value(name, parsed)

        edit.editingFinished.connect(_commit)
        return edit

    def _make_fallback_editor(self, name: str, value: Any) -> QLineEdit:
        try:
            text = json.dumps(value) if value is not None else ""
        except (TypeError, ValueError):
            text = str(value)
        edit = QLineEdit(text)

        def _commit() -> None:
            raw = edit.text().strip()
            if not raw:
                self._set_value(name, None)
                return
            try:
                parsed = json.loads(raw)
            except ValueError:
                parsed = raw  # plain strings need no quoting
            self._set_value(name, parsed)

        edit.editingFinished.connect(_commit)
        return edit

    # ------------------------------------------------------------------
    # Draft synchronisation
    # ------------------------------------------------------------------

    def _set_value(self, name: str, value: Any) -> None:
        try:
            setattr(self._draft, name, value)
        except ValidationError as exc:
            self._flag_error(name, exc.errors()[0]["msg"] if exc.errors() else str(exc))
            return
        editor = self._editors.get(name)
        if editor is not None:
            editor.setStyleSheet("")
        self.value_changed.emit(name, value)

    def _flag_error(self, name: str, message: str) -> None:
        editor = self._editors.get(name)
        if editor is not None:
            editor.setStyleSheet("border: 1px solid red;")
            editor.setToolTip(message)
        self.validation_failed.emit(name, message)


class ConfigFormDialog(QDialog):
    """Modal popup wrapping a :class:`ConfigFormWidget` with OK/Cancel buttons.

    Parameters
    ----------
    model_cls:
        The configuration model class (``SomeEngine.config_model()``).
    initial:
        Initial values shown in the form.
    title:
        Window title (e.g. ``"Configure SVD Pencil Beam"``).
    parent:
        Optional Qt parent widget.
    """

    def __init__(
        self,
        model_cls: type[AlgorithmConfig],
        initial: Optional[Mapping[str, Any]] = None,
        title: str = "Configure",
        parent: Optional[QWidget] = None,
    ) -> None:
        super().__init__(parent)
        self.setWindowTitle(title)

        root = QVBoxLayout(self)
        self._form = ConfigFormWidget(model_cls, initial=initial)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QScrollArea.Shape.NoFrame)
        scroll.setWidget(self._form)
        root.addWidget(scroll, 1)

        self._lbl_status = QLabel("")
        self._lbl_status.setStyleSheet("color: red;")
        root.addWidget(self._lbl_status)
        self._form.validation_failed.connect(
            lambda name, msg: self._lbl_status.setText(f"{name}: {msg}")
        )
        self._form.value_changed.connect(lambda *_: self._lbl_status.setText(""))

        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel
        )
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        root.addWidget(buttons)

        self.resize(420, min(120 + 28 * len(self._form._editors), 600))

    @property
    def form(self) -> ConfigFormWidget:
        """Get the embedded configuration form."""
        return self._form

    def values(self) -> dict[str, Any]:
        """Get the entries that were set initially or edited by the user."""
        return self._form.values()
